name: FunctionalTests
run-name: "Functional Tests run by @${{ github.actor }}, event: ${{ github.event_name }}"
on:
  workflow_call:
  workflow_dispatch:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install Dependencies
        run: npm ci
      - name: Linting
        run: npx eslint .
      - name: Unit tests with coverage
        run: npm run test:coverage
      - name: Upload Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/
